spring.main.banner-mode=off

spring.datasource.url=jdbc:mysql://localhost/sistemato
spring.datasource.username=root
spring.datasource.password=mrlouiz12

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=false

server.servlet.session.timeout=15m
server.link=localhost:8080
server.servlet.context-path=/sistemato

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.nome=Quess Systems Suporte
spring.mail.username=quess.suporte@gmail.com
spring.mail.password=migdkbytegfqfujo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

sistemato.arquivos.pendencias-path=arquivos/pendencias/
sistemato.num-logs=1000
sistemato.num-pendencias=1000